# Name of the Minigame
game-name: Skywars
game-description: Description
command-name: skywars
command-aliases:
  - sw

countdown: 30
required-players: 2
max-players: 10
lobby-spawn:
  world: world
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0
